# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = span.out
SRCS = main.cpp Span.cpp

include ../template.mk

main.cpp: Span.hpp
Span.cpp: Span.hpp
