# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = easyfind.out
SRCS = main.cpp

include ../template.mk

main.cpp: easyfind.hpp
