# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = stack.out
SRCS = main.cpp

include ../template.mk

main.cpp: MutantStack.hpp
MutantStack.hpp: MutantStack.tpp
